// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace OpenEugene.Specs.LittleHelpBook.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Safety_NetServiceDirectoryFeature : object, Xunit.IClassFixture<Safety_NetServiceDirectoryFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Directory.feature"
#line hidden
        
        public Safety_NetServiceDirectoryFeature(Safety_NetServiceDirectoryFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Safety-Net Service Directory", "As a front-room staff member, \r\nI want to access a comprehensive directory of saf" +
                    "ety-net services, \r\nSo that I can quickly find and refer clients to the appropri" +
                    "ate services.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Searching for a Service Given I have access to the safety-net service directory, " +
            "When I search for a service by category, location, or eligibility, Then I should" +
            " see a list of services that match my search criteria.")]
        [Xunit.TraitAttribute("FeatureTitle", "Safety-Net Service Directory")]
        [Xunit.TraitAttribute("Description", "Searching for a Service Given I have access to the safety-net service directory, " +
            "When I search for a service by category, location, or eligibility, Then I should" +
            " see a list of services that match my search criteria.")]
        public async System.Threading.Tasks.Task SearchingForAServiceGivenIHaveAccessToTheSafety_NetServiceDirectoryWhenISearchForAServiceByCategoryLocationOrEligibilityThenIShouldSeeAListOfServicesThatMatchMySearchCriteria_()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Searching for a Service Given I have access to the safety-net service directory, " +
                    "When I search for a service by category, location, or eligibility, Then I should" +
                    " see a list of services that match my search criteria.", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await testRunner.GivenAsync("a populated directory of services,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
await testRunner.WhenAsync("the user inputs search parameters,", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
await testRunner.ThenAsync("the directory should return all relevant services.", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Adding a New Service Listing Given I am an authorized staff member, When I enter " +
            "details for a new safety-net service, Then the service should be added to the di" +
            "rectory and be searchable.")]
        [Xunit.TraitAttribute("FeatureTitle", "Safety-Net Service Directory")]
        [Xunit.TraitAttribute("Description", "Adding a New Service Listing Given I am an authorized staff member, When I enter " +
            "details for a new safety-net service, Then the service should be added to the di" +
            "rectory and be searchable.")]
        public async System.Threading.Tasks.Task AddingANewServiceListingGivenIAmAnAuthorizedStaffMemberWhenIEnterDetailsForANewSafety_NetServiceThenTheServiceShouldBeAddedToTheDirectoryAndBeSearchable_()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Adding a New Service Listing Given I am an authorized staff member, When I enter " +
                    "details for a new safety-net service, Then the service should be added to the di" +
                    "rectory and be searchable.", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
await testRunner.GivenAsync("the user has the necessary permissions,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
await testRunner.WhenAsync("they submit a new service listing,", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
await testRunner.ThenAsync("the directory should update to include the new service.", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Updating an Existing Service Listing Given I am viewing a service listing, When I" +
            " edit the information and save the changes, Then the updated details should be r" +
            "eflected in the directory.")]
        [Xunit.TraitAttribute("FeatureTitle", "Safety-Net Service Directory")]
        [Xunit.TraitAttribute("Description", "Updating an Existing Service Listing Given I am viewing a service listing, When I" +
            " edit the information and save the changes, Then the updated details should be r" +
            "eflected in the directory.")]
        public async System.Threading.Tasks.Task UpdatingAnExistingServiceListingGivenIAmViewingAServiceListingWhenIEditTheInformationAndSaveTheChangesThenTheUpdatedDetailsShouldBeReflectedInTheDirectory_()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Updating an Existing Service Listing Given I am viewing a service listing, When I" +
                    " edit the information and save the changes, Then the updated details should be r" +
                    "eflected in the directory.", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
await testRunner.GivenAsync("an existing service listing,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
await testRunner.WhenAsync("an authorized user makes changes,", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
await testRunner.ThenAsync("the directory should save and display the updated information.", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Removing a Service Listing Given I have identified a service that is no longer av" +
            "ailable, When I remove the service from the directory, Then the service should n" +
            "o longer appear in any search results.")]
        [Xunit.TraitAttribute("FeatureTitle", "Safety-Net Service Directory")]
        [Xunit.TraitAttribute("Description", "Removing a Service Listing Given I have identified a service that is no longer av" +
            "ailable, When I remove the service from the directory, Then the service should n" +
            "o longer appear in any search results.")]
        public async System.Threading.Tasks.Task RemovingAServiceListingGivenIHaveIdentifiedAServiceThatIsNoLongerAvailableWhenIRemoveTheServiceFromTheDirectoryThenTheServiceShouldNoLongerAppearInAnySearchResults_()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Removing a Service Listing Given I have identified a service that is no longer av" +
                    "ailable, When I remove the service from the directory, Then the service should n" +
                    "o longer appear in any search results.", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
await testRunner.GivenAsync("a service is identified as obsolete,", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
await testRunner.WhenAsync("an authorized user removes the listing,", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
await testRunner.ThenAsync("the directory should no longer include that service.", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Safety_NetServiceDirectoryFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await Safety_NetServiceDirectoryFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
